name = "VLBIData"
uuid = "679fc9cc-3e84-11e9-251b-cbd013bd8115"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.5.0-DEV"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
DataManipulation = "38052440-ad76-4236-8414-61389b2c5143"
InterferometricModels = "b395d269-c2ec-4df6-b679-36919ad600ca"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
StructHelpers = "4093c41a-2008-41fd-82b8-e3f9d02b504f"
Uncertain = "b33f403f-199b-472b-b9d0-1cd2092892d0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
ComradeBase = "6d8c423b-a35f-4ef1-850c-862fe21f82c4"
PolarizedTypes = "d3c5d4cd-a8ee-40d6-aac7-e34df5a20044"
VLBISkyModels = "d6343c73-7174-4e0f-bb64-562643efbeca"

[extensions]
ComradeBaseExt = "ComradeBase"
PolarizedTypesExt = "PolarizedTypes"
VLBISkyModelsExt = "VLBISkyModels"

[compat]
AccessorsExtra = "0.1.77"
ComradeBase = "0.8, 0.9"
DataManipulation = "0.1.12"
InterferometricModels = "0.1.24"
IntervalSets = "0.7"
PolarizedTypes = "0.1.2"
Reexport = "1.2.2"
StaticArrays = "1.0"
Statistics = "1"
StructArrays = "0.6.4, 0.7.1"
StructHelpers = "1.3.1"
Uncertain = "0.1.0"
Unitful = "1.5"
VLBISkyModels = "0.6"
julia = "1.6"
